#ifndef ERRORS_H
#define ERRORS_H

#define ERROR_NETWORK_INIT 1
#define ERROR_SNIFFER_START 2
#define ERROR_PACKET_PROCESSING 3
#define ERROR_PCAP 4
#define ERROR_NO_DEVICES 5
#define ERROR_DEVICE_NOT_FOUND 6
#define ERROR_DEVICE_OPEN 7
#define ERROR_DEVICE_UNSUPPORTED 8
#define ERROR_FILTER_COMPILE 9
#define ERROR_SET_FILTER 10
#define ERROR_PROCESSOR_INITIALIZE 11

#endif